[package]
name = "server-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.100", features = ["full", "extra-traits"] }
quote = { version = "1.0.39" }
proc-macro2 = { version = "1.0.94" }
