[workspace]
resolver = "2"
members = ["mtc-model", "mtc-api", "mtc-web"]
default-members = ["mtc-api", "mtc-web"]
exclude = ["mtc-model"]

[workspace.package]
version = "0.1.0"
description = "MTC-CMS"
authors = ["Anatolii Shliakhto <a.shlyalkhto@gmail.com>"]
license = "MIT"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
