version: "3"
services:
  web:
    build:
      context: .
    container_name: mtc-cms
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - data:/mtc-cms/
    env_file:
      - .env
volumes:
  data: