[package]
name = "mtc-wasm"
description = "Military training center CMS WebAssembly"
edition.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
mtc-model = { path = "../mtc-common" }
dioxus = { version = "0.6.0-alpha.2", features = ["web", "router", "default"] }
#dioxus-i18n = { version = "0.2.5" }
dioxus-logger = { version = "0.5.1" }
reqwest = { version = "0.12.7", features = ["json", "brotli", "blocking", "cookies"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.128" }
tracing = { version = "0.1.40" }
gloo-storage = { version = "0.3.0" }
futures-util = { version = "0.3.30" }
csv = { version = "1.3.0" }
simsearch = { version = "0.2.5" }
chrono = { version = "0.4.38" }


